### ISSUE TITLE
Not showing anything

### ISSUE THREAD

**Issue by ghost** [TeddyDD/gterm#1]
Hey Teddy,

Great project u have here. But, nothing seems to show when launched:

![image](https://cloud.githubusercontent.com/assets/10387670/15492153/1350f37c-212d-11e6-85cb-432dcb4c14c4.png)

I'm using the latest nightly build here http://fixnum.org/godot/

Any idea? Thx

**Comment by TeddyDD** [comment]
Hi! Nice to see any interest in my little project. Unfortunately I'v got some werid bug that makes working on this project impossible. When I try to resize game windows then Godot crashes. Could you check if you can reproduce this? Also take a look here https://github.com/godotengine/godot/issues/4641 

This is rewrite of my old project so if you interested in something with similar functionality but without dynamic terminal and font resizing you can take a look at first [version of this project](https://gitlab.com/TeddyDD/Terminal-Godot/tree/master) Here is [imgur album](https://imgur.com/a/9MaYo) if you want to take a look

It's usable but api is quiet simple. Feel free to ask any questions :wink:

**Comment by TeddyDD** [comment]
Hello. I finally manage to fix that bug and implement basic functionality. Now this control have more features than my old version but terminal api is pretty minimal: `write_char` and `write_color`. Font and terminal resizing works like a charm. I also created demo when you can write, change colors and font size so It actually shows things :wink: so I suppose I can close this issue
![zrzut ekranu z 2016-06-04 17-30-00](https://cloud.githubusercontent.com/assets/4397533/15800472/28877386-2a7b-11e6-8b11-e4c2dc4003d0.png)

More extensive API will be coming soon™ as well as more demos, docs and features :)

**Comment by ghost** [comment]
Never knew something like that was possible within Godot, really amazing stuff @TeddyDD
